// <auto-generated />
using System;
using LabelPrint.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabelPrint.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LabelPrintDbContext))]
    [Migration("20260731192108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("LabelPrint.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPrintOrders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRefreshOrders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabasePath")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultLabelHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultLabelWidthMm")
                        .HasColumnType("REAL");

                    b.Property<double>("EditorGridSizeMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("EditorSnapEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontPadBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontPadSecret")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontPadWebhookListenUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryRetentionMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPrintRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersRefreshIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.LabelTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultPrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dpi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeightMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemPreset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WidthMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPrinterId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.ToTable("LabelTemplates", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Employee")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderId")
                        .IsUnique();

                    b.HasIndex("OrderedAt");

                    b.HasIndex("Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalProductId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionTotal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.PrintHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrintJobId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrintedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PrinterId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PrintedAt", "Status");

                    b.ToTable("PrintHistory", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTransientFailure")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RowVersion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceJobId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("PrintJobs", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Darkness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dpi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("PaperWidthMm")
                        .HasColumnType("REAL");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.ToTable("Printers", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderItemTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WeightValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("Barcode IS NOT NULL");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultTemplateId");

                    b.HasIndex("Name");

                    b.HasIndex("OrderItemTemplateId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.ProductCustomField", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "FieldDefinitionId");

                    b.HasIndex("FieldDefinitionId");

                    b.ToTable("ProductCustomFields", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Category", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.LabelTemplate", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.Printer", "DefaultPrinter")
                        .WithMany("Templates")
                        .HasForeignKey("DefaultPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultPrinter");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabelPrint.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.PrintJob", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.Printer", "Printer")
                        .WithMany("PrintJobs")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabelPrint.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.LabelTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("OrderItem");

                    b.Navigation("Printer");

                    b.Navigation("Product");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Product", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.LabelTemplate", "DefaultTemplate")
                        .WithMany()
                        .HasForeignKey("DefaultTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabelPrint.Domain.Entities.LabelTemplate", "OrderItemTemplate")
                        .WithMany()
                        .HasForeignKey("OrderItemTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("DefaultTemplate");

                    b.Navigation("OrderItemTemplate");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.ProductCustomField", b =>
                {
                    b.HasOne("LabelPrint.Domain.Entities.CustomFieldDefinition", "FieldDefinition")
                        .WithMany("Values")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabelPrint.Domain.Entities.Product", "Product")
                        .WithMany("CustomFields")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.CustomFieldDefinition", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Printer", b =>
                {
                    b.Navigation("PrintJobs");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LabelPrint.Domain.Entities.Product", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
